windowrule = opacity 0.8 0.8, class:Alacritty
windowrule = opacity 0.8 0.8, class:code
windowrule = opacity 0.8 0.8, class:discord
# windowrule = opacity 0.8 0.8, class:firefox
windowrule = opacity 0.8 0.8, floating:1