format="$directory$git_branch$character"

# Prompt symbols 
[character]
success_symbol = "[🞈](@{tertiary} bold)"
error_symbol = "[🞈](@{error})"
vicmd_symbol = "[🞈](#f9e2af)"

[directory]
format = "[]($style)[(bg:@{primary} fg:@{on_primary})$path ](fg:@{on_surface_variant} bg:@{surface_variant})[](fg:@{primary} bg:@{surface_variant})[󰉋](bg:@{primary} fg:@{on_primary})[ ](fg:@{primary})"

style = "bg:@{surface} fg:@{surface_variant}"

[git_branch]
format = "[](fg:@{surface_variant})[(bg:@{primary} fg:@{on_primary})$branch ](fg:@{on_surface_variant} bg:@{surface_variant})[](fg:@{primary} bg:@{surface_variant})[](bg:@{primary} fg:@{on_primary})[ ](fg:@{primary})"
style = "bg:@{surface} fg:@{surface_variant}"
