format="$directory$git_branch$character"

# Prompt symbols 
[character]
success_symbol = "[🞈](@{tertiary} bold)"
error_symbol = "[🞈](@{error})"
vicmd_symbol = "[🞈](#f9e2af)"

[directory]
format = "[]($style)[(bg:@{primary} fg:@{surface_variant})$path](bg:@{surface_variant} fg:@{primary})[ ]($style)"
style = "bg:@{surface} fg:@{surface_variant}"

# [git_b# ranch]
# format = "[]($style)[[ ](bg:#89b4fa fg:#49628a bold)$branch](bg:#89b4fa fg:#362f2b)[ ]($style)"
# style = "bg:#1a1b26 fg:#89b4fa"
