[services]
gog = True
egs = True
ea_app = True
ubisoft = True
steam = True

[lutris]
library_ignores = 
migration_version = 16
icon_type_gridview_steam = banner
icon_type_gridview_egs = game_banner_small
icon_type_gridview = coverart_med
width = 1920
height = 1033
maximized = True
selected_category = category:all
show_advanced_options = True
preferred_theme = default

