# Set color defaults
set -g status-bg                          "#130d07"
set -gq @thm_bar_bg                       "#130d07"

set -gq @thm_bg                           "#19120c"
set -gq @thm_fg                           "#eee0d5"
set -gq @thm_primary                      "#fcb974"
set -gq @thm_inverse_primary              "#855318"
set -gq @thm_surface_low                  "#211a14"
set -gq @thm_surface                      "#261e18"
set -gq @thm_surface_variant              "#302921"
set -gq @thm_outline                      "#50453a"
set -gq @thm_text_variant                 "#d5c3b5"

set -g status-style                       "bg=#{@thm_bg},fg=#{@thm_fg}"
set -g window-active-style                "bg=#{@thm_bg},fg=#{@thm_fg}"

set-option -g status-position top

# Source matugen after setting defaults
source-file ~/.config/tmux/generated.conf

# Active window
# setw -g window-status-current-format  "#[bg=#{@thm_bar_bg},fg=#{@thm_primary}]" 
# setw -ga window-status-current-format "#[bg=#{@thm_primary},fg=#{@thm_surface_variant}][#I] "
# setw -ga window-status-current-format "#[bg=#{@thm_surface_variant},fg=#{@thm_primary}] #W"
# setw -ga window-status-current-format "#[bg=#{@thm_bar_bg},fg=#{@thm_surface_variant}] #[none]"

# Inactive window
# setw -g window-status-format          "#[bg=#{@thm_bar_bg},fg=#{@thm_inverse_primary}]" 
# setw -ga window-status-format         "#[bg=#{@thm_inverse_primary},fg=#{@thm_bg}]#I "
# setw -ga window-status-format         "#[bg=#{@thm_surface_variant},fg=#{@thm_inverse_primary}] #W"
# setw -ga window-status-format         "#[bg=#{@thm_bar_bg},fg=#{@thm_surface_variant}] #[none]"

set -g status-bg                          @thm_surface_variant

# Style whatever you wish with the imported colors
# ...
