monitor=,preferred,auto,1

# TODO: Find out why this doesnt work inside autostart.conf
exec-once = ~/.config/hypr/scripts/welcome.sh

source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/windowrules.conf

#device:MSFT0001:00 06CB:CE2D Touchpad {
#    accel_profile = flat
#    sensitivity = 0.8
#}

monitor = eDP-1, 1920x1080@144, 0x0, 1

env = HYPRCURSOR_THEME,McMojave
env = HYPRCURSOR_SIZE,32

input {
    kb_layout = us,ru(phonetic)
    kb_options = grp:win_space_toggle

    numlock_by_default = true
    sensitivity = -0.2

    touchpad {
        natural_scroll = yes
	    disable_while_typing = true
	    tap-to-click = true
    }
}

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 2
    #cursor_inactive_timeout = 0
    
    layout = dwindle
}

cursor {
    inactive_timeout = 0
}

gestures {
    gesture = 3, horizontal, workspace
}

decoration {
    # rounding = 5

    #drop_shadow = false

    dim_inactive = true
    
    blur {
        enabled = true
    }
}

animations {
    enabled = yes
    
    # https://m3.material.io/styles/motion/easing-and-duration/applying-easing-and-duration
    bezier = emphasized, 0.2, 0, 0, 1
    bezier = emphasized_decelerate, 0.2, 0, 0, 1
    bezier = emphasized_accelerate, 0.2, 0, 0, 1
    
    animation = windowsIn, 1, 5, emphasized_decelerate, slide
    animation = windowsOut, 1, 2, emphasized_accelerate, slide
    animation = border, 1, 5, emphasized
    animation = fadeDim, 1, 5, emphasized
    animation = fadeIn, 1, 5, emphasized
    animation = fadeOut, 1, 2, emphasized
    animation = workspaces, 1, 5, emphasized, slide
}

dwindle {
    pseudotile = yes 
    preserve_split = yes 
}

#master {
#    new_is_master = true
#}