# windowrule = opacity 0.8 0.8, class:Alacritty
# windowrule = opacity 0.8 0.8, class:code
# windowrule = opacity 0.8 0.8, class:discord
# # windowrule = opacity 0.8 0.8, class:firefox
# windowrule = opacity 0.8 0.8, floating:1

# windowrule = match:class Alacritty, opacity 0.97 0.97
# windowrule = match:class code, opacity 0.97 0.97
# windowrule = match:class discord, opacity 0.97 0.97
# windowrule = match:class firefox, opacity 0.97 0.97
# windowrule = match:float true, opacity 0.8 0.8

# windowrulev = match:title ^(Picture-in-Picture)$, float
# windowrulev = match:title ^(Picture-in-Picture)$, pin
# windowrulev = match:title ^(Picture-in-Picture)$, noborder
# windowrulev = match:title ^(Picture-in-Picture)$, nodim