# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  hardware.enableRedistributableFirmware = true;

  services.xserver.videoDrivers = ["nvidia"];

  systemd.oomd.enable = true;
  systemd.oomd.enableUserSlices = true;

  zramSwap.enable = true;
  zramSwap.memoryPercent = 50;

  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = true;
    powerManagement.finegrained = false;
    open = true;
    nvidiaSettings = true;
    dynamicBoost.enable = true;
    package = config.boot.kernelPackages.nvidiaPackages.beta;
    # package = let
    #   base = config.boot.kernelPackages.nvidiaPackages.latest;
    #   cachyos-nvidia-patch = pkgs.fetchpatch {
    #     url = "https://raw.githubusercontent.com/CachyOS/CachyOS-PKGBUILDS/master/nvidia/nvidia-utils/kernel-6.19.patch";
    #     sha256 = "sha256-YuJjSUXE6jYSuZySYGnWSNG5sfVei7vvxDcHx3K+IN4=";
    #   };

    #   # Patch the appropriate driver based on config.hardware.nvidia.open
    #   driverAttr =
    #     if config.hardware.nvidia.open
    #     then "open"
    #     else "bin";
    # in
    #   base
    #   // {
    #     ${driverAttr} = base.${driverAttr}.overrideAttrs (oldAttrs: {
    #       patches = (oldAttrs.patches or []) ++ [cachyos-nvidia-patch];
    #     });
    #   };
  };

  boot.loader.systemd-boot = {
    enable = true;
    configurationLimit = 5;
  };

  environment.systemPackages = with pkgs; [
    nvidia-vaapi-driver
    libva-utils
  ];

  boot.loader.efi.canTouchEfiVariables = true;

  # swapDevices = [
  #   {
  #     device = "/var/lib/swapfile";
  #     size = 16 * 1024; # 16 GB
  #     options = ["discard=once"];
  #   }
  # ];

  services.fstrim.enable = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  boot = {
    # kernelPackages = pkgs.linuxPackages_xanmod_latest;
    kernelPackages = pkgs.cachyosKernels.linuxPackages-cachyos-latest-lto-x86_64-v3;
    kernel.sysctl = {
      "kernel.split_lock_mitigate" = 0;
      "kernel.nmi_watchdog" = 0;
      "kernel.sched_bore" = "1";
    };

    kernelParams = [
      "quiet"
      "udev.log_level=3"
      "systemd.show_status=auto"
      "ntsync"
    ];

    plymouth = {
      enable = true;
      themePackages = [pkgs.mac-style-plymouth];
      theme = "mac-style";
    };
    consoleLogLevel = 3;

    initrd = {
      verbose = false;
      availableKernelModules = ["nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod"];
      kernelModules = [];
    };

    kernelModules = [
      "kvm-amd"
      # "lenovo-legion-module"
    ];
    extraModulePackages = [config.boot.kernelPackages.lenovo-legion-module];

    # Hide the OS choice for bootloaders.
    # It's still possible to open the bootloader list by pressing any key
    # It will just not appear on screen unless a key is pressed
    loader.timeout = 0;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0178df82-bedf-46f7-844a-15eee20d014c";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/44CC-C0B2";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/mnt/games" = {
    device = "/dev/disk/by-uuid/DE781DCA781DA1F7";
    fsType = "ntfs-3g";
    options = ["rw" "uid=1000"];
  };

  fileSystems."/mnt/windows" = {
    device = "/dev/disk/by-uuid/ACF0CD28F0CCF99A";
    fsType = "ntfs-3g";
    options = ["rw" "uid=1000"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
