# --- Main Colors ---
background            {{ colors.surface.default.hex }}
foreground            {{ colors.on_surface.default.hex }}
cursor                {{ colors.on_surface.default.hex }}
cursor_text_color     {{ colors.surface.default.hex }}

selection_background  {{ colors.secondary_container.default.hex }}
selection_foreground  {{ colors.on_secondary_container.default.hex }}

url_color             {{ colors.tertiary.default.hex }}

# --- ANSI Colors ---
color0                {{ colors.surface.default.hex }}
color1                {{ colors.error.default.hex }}
color2                {{ colors.tertiary.default.hex }}
color3                {{ colors.secondary.default.hex }}
color4                {{ colors.primary.default.hex }}
color5                {{ colors.tertiary_fixed_dim.default.hex }}
color6                {{ colors.secondary_fixed_dim.default.hex }}
color7                {{ colors.on_surface.default.hex }}

color8                {{ colors.surface_variant.default.hex }}
color9                {{ colors.error_container.default.hex }}
color10               {{ colors.tertiary_container.default.hex }}
color11               {{ colors.secondary_container.default.hex }}
color12               {{ colors.primary_container.default.hex }}
color13               {{ colors.on_secondary_fixed_variant.default.hex }}
color14               {{ colors.on_tertiary_fixed_variant.default.hex }}
color15               {{ colors.on_surface_variant.default.hex }}

# --- Starship Prompt Bubbles ---
color255              {{ colors.primary_container.default.hex }}
color254              {{ colors.primary.default.hex }}
color253              {{ colors.secondary_container.default.hex }}
color252              {{ colors.secondary.default.hex }}
color251              {{ colors.tertiary_container.default.hex }}
color250              {{ colors.tertiary.default.hex }}
color249              {{ colors.error_container.default.hex }}
color248              {{ colors.error.default.hex }}

color232              {{ colors.on_primary_container.default.hex }}
color233              {{ colors.on_primary.default.hex }}
color234              {{ colors.on_secondary_container.default.hex }}
color235              {{ colors.on_secondary.default.hex }}
color236              {{ colors.on_tertiary_container.default.hex }}
color237              {{ colors.on_tertiary.default.hex }}
color238              {{ colors.on_error_container.default.hex }}
color239              {{ colors.on_error.default.hex }}
color240              {{ colors.on_primary_container.default.hex }}

# Matched with unthemed light/dark
color243              {{ colors.primary.default.hex }}
color244              {{ colors.error.default.hex }}
color245              {{ colors.outline_variant.default.hex }}

# --- UI Elements ---
active_tab_foreground   {{ colors.on_primary.default.hex }}
active_tab_background   {{ colors.primary.default.hex }}
inactive_tab_foreground {{ colors.on_primary_container.default.hex }}
inactive_tab_background {{ colors.primary_container.default.hex }}

active_border_color     {{ colors.primary.default.hex }}
inactive_border_color   {{ colors.outline.default.hex }}

# --- Marks ---
mark1_foreground        {{ colors.on_primary_fixed.default.hex }}
mark1_background        {{ colors.primary_fixed.default.hex }}
mark2_foreground        {{ colors.on_secondary_fixed.default.hex }}
mark2_background        {{ colors.secondary_fixed.default.hex }}
mark3_foreground        {{ colors.on_tertiary_fixed.default.hex }}
mark3_background        {{ colors.tertiary_fixed.default.hex }}
